# Generated by Django 4.0.3 on 2023-06-11 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('favorites', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('memo', models.TextField(null=True)),
                ('version', models.IntegerField(default=1)),
                ('removed', models.BooleanField(default=False)),
                ('s3key', models.CharField(max_length=255, null=True)),
                ('clicked', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('shared_with', models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
    ]
